[package]
name = "spwn-CMPL"
version = "1.0.0"
edition = "2018"

[[bin]]
name = "out"
path = "container_src/main.rs"

[profile.release]
opt-level = 3

[dependencies]
rev_buf_reader = "0.2.0"
unzpack = "0.1.0"
